### Create Package (Porteiro recebe)
POST http://localhost:3000/packages
Content-Type: application/json

{
  "description": "Caixa da Amazon",
  "trackingCode": "AMZ123ABC",
  "apartmentId": "{{apartment_id}}",
  "receivedByUserId": "{{user_id}}"
}

### Get Package by id
GET http://localhost:3000/packages/{{package_id}}

### List all Packages of an Apartment
GET http://localhost:3000/packages/apartment/{{apartment_id}}

### List only Available Packages of an Apartment
GET http://localhost:3000/packages/apartment/{{apartment_id}}/available

### Withdraw Package (Morador retira)
POST http://localhost:3000/packages/{{package_id}}/withdraw
Content-Type: application/json

{
  "withdrawnByResidentId": "{{resident_id}}",
  "withdrawalPhotoUrl": "https://exemplo.com/foto-carteirinha.jpg",
  "similarityScore": 0.95
}
